[package]
name = "branch1"
version = "1.0.0"
description = "Branch1 Desktop"
authors = ["Branch1"]
edition = "2021"

[lib]
name = "branch1_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
